consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Json:
    description: An message (default view)
    example:
      content: Aliquam omnis.
      title: Esse at perspiciatis ex.
    properties:
      content:
        description: message content
        example: Aliquam omnis.
        type: string
      title:
        description: message title
        example: Esse at perspiciatis ex.
        type: string
    title: 'Mediatype identifier: application/json; view=default'
    type: object
  JsonCollection:
    description: JsonCollection is the media type for an array of Json (default view)
    example:
    - content: Aliquam omnis.
      title: Esse at perspiciatis ex.
    - content: Aliquam omnis.
      title: Esse at perspiciatis ex.
    items:
      $ref: '#/definitions/Json'
    title: 'Mediatype identifier: application/json; type=collection; view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: The initial service for StatNLP
  title: The initial service
  version: ""
paths:
  /api/messages:
    get:
      description: get all messages
      operationId: message#list
      produces:
      - application/json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JsonCollection'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list message
      tags:
      - message
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
