// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "intital": swagger TestHelpers
//
// Command:
// $ goagen
// --design=statnlp-initializer-service-go/design
// --out=$(GOPATH)/src/statnlp-initializer-service-go
// --version=v1.3.1

package test
